#!/bin/sh -e

if [ "$1" = configure ]; then
	if ! grep -qE '^root:\$' /etc/shadow; then
		echo mdvl-banana-pi-m2-plus-edu-root: setting root password...
		( echo testwort; echo testwort ) | passwd
	fi
	if ! grep -qF linux-fan /etc/passwd; then
		echo mdvl-banana-pi-m2-plus-edu-root: adding user linux-fan...
		useradd -m linux-fan
		( echo testwort; echo testwort ) | passwd linux-fan
	fi
	echo mdvl-banana-pi-m2-plus-edu-root: generating system files...
	echo bananapim2p > /etc/hostname
	echo nameserver 8.8.4.4 > /etc/resolv.conf
	cat > /etc/network/interfaces <<EOF
auto lo
iface lo inet loopback

allow-hotplug eth0
auto eth0
iface eth0 inet dhcp
EOF
fi
